<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Module Default Path
    |--------------------------------------------------------------------------
    |
    | This option defines the default path where modules will be created.
    | You can change this to organize modules in a different structure.
    |
    */
    'path' => 'App',

    /*
    |--------------------------------------------------------------------------
    | Generate Views by Default
    |--------------------------------------------------------------------------
    |
    | This option defines whether views should be generated by default.
    | Set to true to generate views automatically.
    |
    */
    'generate_views' => false,

    /*
    |--------------------------------------------------------------------------
    | View Path
    |--------------------------------------------------------------------------
    |
    | This option defines the default path where views will be created.
    |
    */
    'view_path' => 'resources/views',

    /*
    |--------------------------------------------------------------------------
    | Default Module Type
    |--------------------------------------------------------------------------
    |
    | This option defines the default module type to generate.
    | Options: 'full', 'api', 'model-migration'
    |
    */
    'default_type' => 'full',

    /*
    |--------------------------------------------------------------------------
    | Add Routes by Default
    |--------------------------------------------------------------------------
    |
    | This option defines whether routes should be added by default.
    |
    */
    'add_routes' => true,

    /*
    |--------------------------------------------------------------------------
    | Default API Version
    |--------------------------------------------------------------------------
    |
    | This option defines the default API version to use for API controllers.
    | Set to null to not use versioning.
    |
    */
    'api_version' => 'v1',
];
